sudo: required
language: python
python:
- '3.7'
dist: xenial
services:
- docker
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
before_install:
- echo $TOKEN | gpg --passphrase-fd 0 credentials.tar.gz.gpg
- tar -xzf credentials.tar.gz
- rm credentials.tar.gz
install:
- pip install pipenv
- pipenv install --dev --skip-lock
script:
- pipenv run pytest --cov=./ --show-progress
- pipenv run coveralls
before_deploy:
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud components install kubectl
- gcloud --quiet components update
deploy:
- provider: script
  script: chmod +x $TRAVIS_BUILD_DIR/k8s/deploy.sh && sh $TRAVIS_BUILD_DIR/k8s/deploy.sh
  skip_cleanup: true
  on:
    branch: k8s/production
env:
  global:
  - secure: mUlx77blA7+wPmjUaHpLnwcJrYBl3xcYpR71kSLqw3qa6Sh9x8e6BHG1n4EgAcbrVRxr8F+VL9FAxc8XPLXHkHZs+6VoFiMm7tWLn88Hv5iH+yxg/SklxbFUi1m1Ae35hPfdNmJdMggawc31IKWH/luIECjBmAy9+tjaQBE5rxlly+Huwiy/CyNfk2GlhpocwUIxrdZTdBDOXaRPmZ3mhiCTWCeCdlzFa6wOcjPitk5uVCcrDWW+v8HzFqsQMqGRwjKdett8APUmPKJ52Jvgk5VOCqYxkBprJvx2eAJLVuKC5YqcpfiA3YV+tR5nRXB17XywUOAeFeoF9bgVOfIYFus86mxjR0lfmbp39jb9Y/nzfs6WlndEhLOvULOFrlA2uOCm2c/OQGB/CyZJ2WOs18cbcUc1a4qA5nKjTvBSeI6TD2n98dmzye43hHLaAYhGIDhF+iIIIwxvCdrKNyiBtdp5B7d5LG+u29p8xqagqLksR8koVAVwW8FaDI2EWA/j4TqECNd++05XS7S78DQdwBnotR3HjdRKi4S3BM5E8CUA9Zd0wb64Xcgd9a4RFevGfsENkxt3GHWksgyCk4fmuykjSyQ4Abd7h1jRHG1HUexpxzOcbo03HaQzp9MAEtMPIukbeHcpAhPlM21nLhP3n/k9+oUW9cwvSZTZA191ZQM=
  - secure: U7mEZ0fHFeH8bnMaN9Nvv4sd3jkpiqaDc5Jcx/+lKpcgmXObqmRqdWw9AZ/XpDAT8ddTmfCVjUMvD5+VRdxwBcX7dyzbU9R7WkcWq8W/5gI/B+2hE9CLshEjn9pikbMHkG/Run9dbNlQ4K1IQk46+p1qPPH/MRnYTsZr2MWbJqFTlAetNXMfrFLeZBZpBVw13DMh5b1jhzgfFkqjUjGqY/RrJCojxOWhI7LCXRomlRtpMILLjfKZyFamje0fZO4+Zl39Tw6UYfPQKvSEYzUkowX17x9i7fzT+d2NQWEMx8ErdwCmhHM7/0OCOsxK98a4V2lEmzuahyi8HOQEtCVVTQBA70hZH8lcNXEYODi3wNzeMDREDkstBvQVryJXkrN6mbX61H7rA00w8bs1LAU85tV63sOuWqJ44lKHAIQ3ksmfvc6nUtxzxINJ+h5JYf30t4NJiHcgmY8xpM6TqnsMuZRpKCbzfcRRKg+EQqahrFC37ybr1zZt4csyeyLZXxhHTvjx8cYePZFdM2rqbGFUpWXjZegpTqnqUfkIpG5VtB00qQgtFBCmbYyCDXfaRSz0ZnaRjeIEQypdHspWolphyP7V9dm60vEhVujQNddoXseZt4cB1QCZMSmlN21kEelCh0MUOS0er352AnU0aRTaVcizwSuSo76j+hgytJ9c/eU=
  - secure: kTq06HNHyEPYBXiyOq0Q6sydV5Wl41Wza7hhsXU1Hol4JThtJ/9/9N5eRksLoY8cqMmDgqiAf1BxsrFS/8NA/L6Rhefn32B0Oo2cl72Zt30dFO8/Yulpq1pYmJI/ZhLlWXUJ6Oxr/wtPWQOiHYk1xZ3dCJr51guBDAW/Kw8a6wQJSuT6VvfXNS34sKSv7HLBJ3OLrheBlccGR2ADCO1Xpn8qxIjUXS7PV1fLhEQbc5qxH0uy4G+aItmNJSKjnc28KAm1439ps5cLZjP3WboPO5lzNu0KDDMlhGXWrcpcqubpExdYJMfkrNOxS3SpRg87L86utuJHEwcxRw27ypx7OQqYrH0osu9lzwgJJSniE5Jcw/F951/GILFSFWVDLHtnYbkUjiqT4Ttpw9x5Ue2Gf4UzY7iRJi7CFI/i4EKb3Xlx1jWZNIlV+jpd42E0YIRauESo9aMYlK4JhSuyW2JjXCRva8IOj55nH6xlk6R2X2WDh6LbfAVo8WiwrFLNYdj3nZhc5ED2jfxEqvOnDwsiAlbHXoN6IeoW+YVQd3tyAx5qjTQIuy7Jyhblm5t4/R7/HAr6KtAqVb0DCUH2lPU4mpGAM5pjAGb2gY4Y+3LaT9HRJAZjmPfx5agxfqxkkTKD3/JaxMsZdZeLzZqxUIMi3yaOLLqiZtn3ESmnrnXoJNw=
